### ISSUE TITLE
LED doesn't flash [Solved: lacked LED_PRESENT in user's bootloaderconfig.h]

### ISSUE THREAD

**Issue by dunk8888** [gblargg/usbasploader#1] opened 2017-08-28 17:56 UTC
Hi me trying get the led to flash on bootloader,i see there is an option for it and ive configured it to PB5 but it doesnt work,how do i enable it to work? does it work as standard? do i have to copy the define anywhere?thanks

**Comment by gblargg** [comment] 2017-08-30 02:06
I'm not sure (haven't worked on AVR stuff for a few years). It doesn't look like the code ever sets the LED pin's DDR as output. You could try modifying postconfig.h to force the LED pin as output:

// line 129
	#define LED_INIT()		{ USB_DDRPORT(LED_PORT) |=  (1<<LED_BIT); }

It seems like it should have done this all along. Let me know how that works.

**Comment by dunk8888** [comment] 2017-09-02 20:40
Hi i tryed that allready,ive tryed everything,ime using an led on pin pb5 ive tryed gnd and vcc and messed with code so its active high and active low,its mind boggling.
The code below toggles the led doesnt it?
{ USB_DDRPORT(LED_PORT) ^= (1<<LED_BIT); }// toggle led
The code below pulls the led low right?
{ USB_DDRPORT(LED_PORT) &= ~(1<<LED_BIT); } // led low/off

It says in code led has to go to vcc not gnd,does that matter? I know it depends on code too,like if led was on vcc you would have to pull pin low to turn it on and if gnd you would have to pull pin up to turn it on,thats right isnt it.Ive tryed eather way anyway,so does the code below looks ok?

#if LED_PRESENT
	#define LED_INIT()		{ USB_DDRPORT(LED_PORT) |= (1<<LED_BIT); }//output
	#define LED_EXIT()		{ USB_DDRPORT(LED_PORT) &= ~(1<<LED_BIT); }//led low/off
        #define LED_BLINK()         { USB_DDRPORT(LED_PORT) ^= (1<<LED_BIT); }// toggle led
And code bellow would turn led on?Is that right?
{ USB_DDRPORT(LED_PORT) |= (1<<LED_BIT); }// led high/on.
or does it need to be like this
{ USB_DDRPORT(LED_PORT) |= ~ (1<<LED_BIT); }// led high/on.
what does this ~ do? 
I know this  |=   is high, what i dont under stand is it output too? or is this output  |=~.
if this means output { USB_DDRPORT(LED_PORT) |= (1<<LED_BIT); } is it output hight at the same time?

**Comment by dunk8888** [comment] 2017-09-02 20:41
Not sure why there are lines through it above,not suposed to be there lol.

**Comment by gblargg** [comment] 2017-09-02 21:00
Does the bootloader work otherwise, just not the LED flashing feature? Can you try with another pin to see whether there's something about that pin in particular? These might help narrow it down in case it's not something with the LED flashing code.

My code actually just toggles the direction bit (DDR, data direction register) of the pin (input/output). This way it toggles between outputting low and floating. This seems safer than toggling between high and low, in case the pin is tied low or something external is driving it mistakenly. I do notice that the code doesn't initialize the actual value on the port, assuming it powers up with zero in the actual port register.

This will ensure that the pin outputs low to turn the LED on, in case it powers on with another value:

	#define LED_INIT() { USB_OUTPORT(LED_PORT) &= ~(1<<LED_BIT); }

One other possibility that comes to mind is the pin being configured for some other unit within the chip, which is overriding it as a basic I/O pin. On several chips it can act as an SPI pin, though SPI shouldn't be enabled by default.

You could try a standalone program that just flashes the LED once a second to be sure that pin works etc.

	#include <avr/io.h>
	#include <util/delay.h>

	#define LED_PORT PORTB
	#define LED_DDR  DDRB
	#define LED_BIT  5

	int main( void )
	{
		LED_PORT &= ~(1<<LED_BIT);
	
		while ( 1 ) 
		{
			LED_DDR ^= 1<<LED_BIT; 
			_delay_ms( 500 );
		}
	
		return 0;
	}

**Comment by dunk8888** [comment] 2017-09-03 03:03
Hi,firstly ide like to say thanks for your time with this,yes bootloader works a treat,ive made a board and have the led in place for the bootloader status,its no big deal it not wrking but it would be a nice feture to have,also its bugging me now lol .
Ive tried other pins too,and run a simple blink and the pin and led are fine on my hardware,i see you have put 
USB_DDR and NOT LED_DDR is that right? Ive even tryed the way that micronucleus has done it but got errors so i must of missed understood somthing
I use the led bootloader status option in micronucleus for my digisparks too. 
My led comes from the pin to gnd through a resistor so its got to be high o come on,ive also tryed it to vcc too.

**Comment by dunk8888** [comment] 2017-09-03 03:49
Do i need to add LED PRESENT in bootloader.h where you have to put #define BOOTLOADER_ON_POWER 1
or whatever config i want,am i not understanding how to enable it? or have you enabled on as standard? I know you used port PC 1 for led but ive tryed that too but ive now using PB 5.

**Comment by gblargg** [comment] 2017-09-03 03:54
I can look over your code and try to reproduce the problem here. What chip are you using?

**Comment by gblargg** [comment] 2017-09-03 13:21
I appreciate you bringing this up and am happy to help figure this out, regardless of whether issue turns out to be in my code or your setup.

Definitely add LED_PRESENT to your bootloaderconfig.h file:

	// Flash LED connected to specified port and pin/bit. LED must go to +V, not GND.
	#define LED_PRESENT 1
	#define LED_PORT B
	#define LED_BIT  5

The USB_DDRPORT and USB_OUTPORT are macros from usbdrv, which convert the port letter into the proper register name (e.g. USB_DDRPORT(B) turns into DDRB). They allow you to specify the port letter in one place rather than multiple places, adhering to the don't-repeat-yourself (DRY) principle. The USB_ prefix is just because it's part of usbdrv, to avoid clash with a similar macro from another library.

Just in case you haven't tried, be sure to try the LED in all four possibilities: pin to ground, both ways (an LED is polarized), pin to +V, both ways. Also be sure the resistor isn't greater than 10k or so (brown black orange, or brown black red for 1k).

**Comment by dunk8888** [comment] 2017-09-03 13:32
Ime using 328P ive emailed you the code,yes ive tryed led all ays as you have said,ime going to try add LED_PRESENT in bootloaderconfig.h i tryed before i think,i may have added the 1 to LED_PRESENT 1.

**Comment by dunk8888** [comment] 2017-09-03 13:39
When i add LED_PRESENT 1 to bootloaderconfig.h file i get error below,

main.c: In function 'main':
main.c:371: warning: implicit declaration of function 'bootLoaderInit'
MAKE: *** [hex] Error 1

C:\Users\Dunk\Desktop\usbasploader with configs 16mhz>make
In file included from main.c:24:
postconfig.h:119:109: error: #if with no expression
make: *** [hex] Error 1

C:\Users\Dunk\Desktop\usbasploader with configs 16mhz>make
main.c:61: error: expected identifier or '(' before '{' token
main.c: In function 'leaveBootloader':
main.c:308: error: 'DDRLED_PORT' undeclared (first use in this function)
main.c:308: error: (Each undeclared identifier is reported only once
main.c:308: error: for each function it appears in.)
main.c:308: error: 'LED_BIT' undeclared (first use in this function)
main.c: In function 'initHardware':
main.c:355: error: 'DDRLED_PORT' undeclared (first use in this function)
main.c:355: error: 'LED_BIT' undeclared (first use in this function)
main.c: In function 'main':
main.c:386: error: 'DDRLED_PORT' undeclared (first use in this function)
main.c:386: error: 'LED_BIT' undeclared (first use in this function)
make: *** [hex] Error 1

C:\Users\Dunk\Desktop\usbasploader with configs 16mhz>

**Comment by gblargg** [comment] 2017-09-03 13:53
I looked over your code and I see the issue. You need to copy/paste the lines from bootloaderconfig-palette.h to bootloaderconfig.h as noted above.

I've committed a small change to postconfig.h which allows a custom LED_BLINK macro so you can tie the LED to GND. With the new version, add these to your bootloaderconfig.h:

	#define LED_PRESENT 1
	#define LED_PORT B
	#define LED_BIT 5

	#define LED_INIT()	   {\
		USB_OUTPORT(LED_PORT) |=  (1<<LED_BIT);\
		USB_DDRPORT(LED_PORT) |=  (1<<LED_BIT);\
	}

	#define LED_EXIT()	   {\
		USB_OUTPORT(LED_PORT) &= ~(1<<LED_BIT);\
		USB_DDRPORT(LED_PORT) &= ~(1<<LED_BIT);\
	}

	#define LED_BLINK()	   { USB_OUTPORT(LED_PORT) ^=  (1<<LED_BIT); }

This will then alternate PB5 between +V and GND, and then float the line on exit.

**Comment by gblargg** [comment] 2017-09-03 13:56
bootloaderconfig-palette.h is never compiled. It's just a palette of lines you can copy and paste into your bootloaderconfig.h file.

**Comment by dunk8888** [comment] 2017-09-03 15:22
Hi,thats sorted it,thanks verry much for your time on this,I can now see it for my self,i was verry close before to getting it right,but i kept changing to many things,now i can get on with my main design,ime planning on making a usb based ws2812b controller,based on this bootloader for easy uploading of code,and then plug the loader into powerbank and watch ws2812b patterns quick and easy,i may sell a few on ebay,witch leads me to my next question,am i able to include this loader in my product to sell? or would i have to sell my board empty and have people load the firmware them selves,i know there are rules with open source and sale of products where code is used in the item.thanks again for your time :-)))

**Comment by gblargg** [comment] 2017-09-03 22:20
Please feel free to use this. It's based on usbasploader, so it's licensed under the GPL. My understanding is that this only requires that you provide the source code for the bootloader (usbasploader) if anyone requests it (and I think you need to mention to buyers in the listing etc. that it uses usbasploader and is under the GPL). So basically just the stock usbasploader code + your configuration files.

I do NOT think that it requires that you release the source code for your own software that you load on. You can keep that private.

This reminds me how cool these AVR chips are. They're so low-cost, and usbdrv gives even the low-end ones USB capability, and then usbasploader makes them reprogrammable with minimal impact. I use this on all my little development sticks.

Good luck with the product and thanks for the feedback and chance to revisit this!

**Closed as completed** 2017-09-03 22:46 UTC
